name: Linux

on:
  push:
    branches:
    - master
    - 'feature/*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    container:
      image: swift:5.6-focal
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - run: swift build -v -c release -Xswiftc -static-stdlib -Xlinker -lCoreFoundation -Xlinker -lCFURLSessionInterface
    - run: chmod -R go+rx .build
    - uses: actions/upload-artifact@v2
      with:
        name: BlinkTool
        # `release` is a symlink, apply glob as a workaround for https://github.com/actions/upload-artifact/issues/92
        path: |
          .build/release*/BlinkTool
          !.build/release?*

  test:
    runs-on: ubuntu-latest
    container:
      image: swift
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - run: swift test -v --enable-test-discovery
    - run: chmod -R go+rx .build
